In [3]:
import torch

# 定义张量

In [12]:
#定义一个尺寸为（5,3）的二阶张量
x = torch.ones(5,3)
print(x)

#定义一个尺寸为（1,5,3）的三阶张量
y = torch.zeros(1,5,3)
print(y)

#定义一个尺寸为（1,2,5,3）的四阶张量
z = torch.randn(1,2,5,3)
print(z)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
tensor([[[[ 1.7715, -1.9737, -0.3431],
          [ 0.2098, -0.2523, -0.1424],
          [ 1.3488, -0.7662, -0.1890],
          [-0.8312,  0.4030,  0.7720],
          [ 0.9848, -0.2217,  0.2031]],

         [[ 0.9168,  0.3324,  0.9744],
          [ 0.8477,  0.2665, -0.6254],
          [-0.6882,  0.3890,  1.8701],
          [-0.3914, -2.1947, -0.3529],
          [-0.9043,  0.2378,  1.9893]]]])


# 访问张量

In [16]:
a = torch.randn(3,4)
print(a)
print("---- 访问张量")

# 通过切片访问：第三列的所有元素
a[:,2]

# 通过索引访问：第二行第三列的元素
a[1,2]

tensor([[-0.4788,  0.4213, -1.4437,  0.7774],
        [ 0.8531,  0.0939, -0.2082, -0.0611],
        [ 2.6093, -0.8995, -0.1357, -0.3704]])
---- 访问张量


tensor(-0.2082)

# 张量运算